server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: hw_inv
    static_configs:
      - targets:
          - localhost
        labels:
          job: hw_inv
          __path__: /reports/build/**/*_hardware_inv.txt
  - job_name: fw_inv
    static_configs:
      - targets:
          - localhost
        labels:
          job: fw_inv
          __path__: /reports/build/**/*_firmware_inv.xml
  - job_name: update_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: update_log
          __path__: /reports/build/**/*_update_log.txt
    pipeline_stages:
    - match:
        selector: '{job="update_log"}'
        stages:
        - regex:
                expression: '(?:Model:)(?P<Model>(.*))'
        - labels:
            Model:
            #SVC TAG:
            #Update start time:
            #Elapsed time:
            #Update end time:
            #protocol:
            #status:
            #body_bytes_sent:
            #http_referer:
            #http_user_agent:




