---
version: "3.7"

services:
  instapxe-tftp:
    image: instapxe/instapxe
    container_name: instapxe-tftp
    restart: always
    env_file:
      - production.env
    ports:
      - 69:69/udp
    volumes:
      - ./tftp:/instapxe/boot
      - ./2_config/menufiles/instapxe.menu:/instapxe/instapxe.menu
      - ./2_config/menufiles/instapxe.menu64:/instapxe/instapxe.menu64
  instapxe-http:
    image: nginx:alpine
    container_name: instapxe-http
    ports:
      - 80:80
    volumes:
      - ./2_config/nginx.cfg/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./http:/usr/share/nginx/html
      - ./nfs/reports:/usr/share/nginx/html/reports
  instapxe-nfs:
    image: erichough/nfs-server
    container_name: instapxe-nfs
    privileged: true
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    volumes:
      - ./nfs/exports:/etc/exports
      - ./nfs/dsu:/dsu
      - ./nfs/sum_gen8:/sum_gen8
      - ./nfs/sum_latest:/sum_latest
      - ./nfs/reports:/reports
      - ./nfs/instapxe_agent:/instapxe_agent 
  instapxe-db:
    image: mysql
    container_name: instapxe-db
    restart: always
    env_file:
      - production.env
    ports:
      - 3306:3306
    volumes:
      - ./db/instapxe_db:/var/lib/mysql
  instapxe-backend:
    build: ./1_src/web/backend
    container_name: instapxe-backend
    restart: always
    env_file:
      - production.env
    ports:
      - 5000:5000
    volumes:
      - ./1_src/web/backend:/instapxe-app
