---
version: "3.7"

services:
  instapxe-tftp:
    image: instapxe/instapxe
    container_name: instapxe-tftp
    restart: unless-stopped
    env_file:
      - production.env
    cap_add:
      - NET_ADMIN
    volumes:
      - ./2_config/instapxe-tftp.cfg/dnsmasq.conf:/pxe/dnsmasq/dnsmasq.conf
      - ./2_config/instapxe.conf:/var/opt/instapxe
    network_mode: "host"

  instapxe-http:
    image: nginx:alpine
    container_name: instapxe-http
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./2_config/nginx.cfg/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./http:/usr/share/nginx/html
      - ./nfs/reports:/usr/share/nginx/html/reports
    networks:
      - instapxe_net

  instapxe-nfs:
    image: erichough/nfs-server
    container_name: instapxe-nfs
    restart: unless-stopped
    privileged: true
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    volumes:
      - ./nfs/exports:/etc/exports
      - ./nfs/dsu:/dsu
      - ./nfs/sum_gen8:/sum_gen8
      - ./nfs/sum_latest:/sum_latest
      - ./nfs/reports:/reports
      - ./nfs/instapxe_agent:/instapxe_agent
    networks:
      - instapxe_net

  instapxe-db:
    image: mysql
    container_name: instapxe-db
    restart: unless-stopped
    env_file:
      - production.env
    ports:
      - 3306:3306
    volumes:
      - ./db/instapxe_db:/var/lib/mysql
    networks:
      - instapxe_net

  instapxe-backend:
    image: instapxe/instapxe-backend
    container_name: instapxe-backend
    restart: unless-stopped
    env_file:
      - production.env
    ports:
      - 9010:9010
    volumes:
      - ./2_config/instapxe.conf:/instapxe
    networks:
      - instapxe_net
    depends_on:
      - instapxe-db

networks:
  instapxe_net:
    driver: bridge
