---
version: "3.7"

services:
  instapxe:
    image: instapxe/instapxe
    container_name: instapxe
    restart: always
    environment:
      - HTTP_HOST=$HOST_IP
      - NFS_HOST=$HOST_IP
      - WDS_HOST=$WDS_IP
    ports:
      - 69:69/udp
    volumes:
      - ./boot:/instapxe/boot
      - ./src/config/menufiles/instapxe.menu:/instapxe/instapxe.menu
      - ./src/config/menufiles/instapxe.menu64:/instapxe/instapxe.menu64
  instapxe-http:
    image: nginx:alpine
    container_name: instapxe-httpd
    ports:
      - 80:80
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./http/dsu:/usr/share/nginx/html/boot/dsu
      - ./http/DUP_REPO:/usr/share/nginx/html/DUP_REPO
      - ./nfs/reports:/usr/share/nginx/html/reports
  instapxe-nfs:
    image: erichough/nfs-server
    container_name: instapxe-nfsd
    privileged: true
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    volumes:
      - ./config/exports:/etc/exports
      - ./nfs/dsu:/dsu
      - ./nfs/spp:/spp
      - ./nfs/reports:/reports
  instapxe-db:
    image: mysql
    container_name: instapxe-db
    restart: always
    environment:
      - MYSQL_USER=instapxe
      - MYSQL_PASSWORD=instapxe
      - MYSQL_ROOT_PASSWORD=instapxe
      - MYSQL_DATABASE=instapxe
    ports:
      - 3306:3306
    volumes:
      - ./data/instapxe_db:/var/lib/mysql
