#!/bin/sh


ln -sf /var/run/rsyslog/dev/log /dev/log

PATHS="/tftpboot/bios /tftpboot/efi32 /tftpboot/efi64"
for i in $PATHS
do	
	echo "MENU INCLUDE pxelinux.cfg/pxe.conf" >> $i/pxelinux.cfg/default
done

exec in.tftpd "$@"
