#!/bin/sh


ln -sf /var/run/rsyslog/dev/log /dev/log

PATHS="/var/opt/instapxe/bios /var/opt/instapxe/efi32 /var/opt/instapxe/efi64"
for i in $PATHS
do	
	if [ ! $(head -5 $i/pxelinux.cfg/default | grep -qxF 'MENU INCLUDE pxelinux.cfg/instapxe.conf)') ]; then 
		cp $i/pxelinux.cfg/default /tmp/tmpdefault
		sed -i '/vesamenu.c32.*/a MENU INCLUDE pxelinux.cfg\/instapxe.conf' /tmp/tmpdefault
		cp /tmp/tmpdefault $i/pxelinux.cfg/default 
		rm /tmp/tmpdefault
	fi
done
exec in.tftpd "$@"
