#!/bin/sh

timestamp() {
  date +"%m/%d/%Y-%H:%M:%S" # current time
}


INSTALLDIR="/var/opt/instapxe"
PATHS="$INSTALLDIR/bios $INSTALLDIR/efi32 $INSTALLDIR/efi64"
for i in $PATHS
do
        #check for user mounted volume
        if [ -d /instapxe ]; then
                if [ -d /instapxe/boot ]; then
                        cp -R /instapxe/boot $i/boot 
                fi
                if [ -f /instapxe/instapxe.menu ] && [[ $i == $INSTALLDIR/bios ]]; then
                        #cp /instapxe/instapxe.menu $i/pxelinux.cfg/default
                        ln -s $i/pxelinux.cfg /instapxe.conf/bios
			envsubst < /instapxe/instapxe.menu > $i/pxelinux.cfg/default
                fi
                if [ -f /instapxe/instapxe.menu32 ] && [[ $i == $INSTALLDIR/efi32 ]]; then
                        #cp /instapxe/instapxe.menu32 $i/pxelinux.cfg/default
                        ln -s $i/pxelinux.cfg /instapxe.conf/uefi32
			envsubst < /instapxe/instapxe.menu32 > $i/pxelinux.cfg/default

                fi
                if [ -f /instapxe/instapxe.menu64 ] && [[ $i == $INSTALLDIR/efi64 ]]; then
                        #cp /instapxe/instapxe.menu64 $i/pxelinux.cfg/default
                        ln -s $i/pxelinux.cfg /instapxe.conf/uefi64
			envsubst < /instapxe/instapxe.menu64 > $i/pxelinux.cfg/default

                fi
        fi
        #check for splash
        if ! [ $(head -5 $i/pxelinux.cfg/default | grep -qxF 'MENU INCLUDE pxelinux.cfg/instapxe.conf)') ]; then
                cp $i/pxelinux.cfg/default /tmp/tmpdefault
                sed -i '/.*menu.c32.*/a MENU INCLUDE pxelinux.cfg\/instapxe.conf' /tmp/tmpdefault
                cp /tmp/tmpdefault $i/pxelinux.cfg/default
                rm /tmp/tmpdefault
        fi


done

echo `timestamp` "- instaPXE started."

