#!/bin/sh



# Get the ip address of this container
#[ "$pxe_nic" ] || pxe_nic="eth0"
_pxe_ip="$(ip -4 -o address show "$pxe_nic" | tr -s ' ' | cut -d' ' -f4 | sed -e 's|/.*||g')"


# Set any optional flags for dnsmasq
[ "$_dnsmasq_flags" ] || _dnsmasq_flags="$@"


# Make sure we have a folder where to store dnsmasq.conf
mkdir -p "/pxe/dnsmasq"

#setup envsubst
[ -e "/pxe/dnsmasq/dnsmasq.conf" ] && cp /pxe/dnsmasq/dnsmasq.conf /tmp/dnsmasq.conf && envsubst < /tmp/dnsmasq.conf > /pxe/dnsmasq/dnsmasq.conf

# Append to default dnsmasq.conf
[ -e "/pxe/dnsmasq/dnsmasq.conf" ] || echo "

# permit bind to regular ports < 1024
user=root

# disable dns server
port=0

# enable tftp server
enable-tftp
tftp-root=/var/opt/instapxe

# dhcp proxy mode. do not act as the authoratitive dhcp server
dhcp-range=${_pxe_ip},proxy

# send disable multicast and broadcast discovery, and to download the boot file immediately
dhcp-option=vendor:PXEClient,6,2b

# when dhcp-range mode=proxy, the filename to download. here the .0 is ommited as it gets auto-added
pxe-service=X86PC,      instaPXE: BIOS mode, bios/instapxe
pxe-service=BC_EFI,      instaPXE: UEFI mode, efi64/instapxe.efi
pxe-service=X86-64_EFI,       instaPXE: UEFI-64 mode, efi64/instapxe.efi


# enable logging
log-queries
log-dhcp

" >> /pxe/dnsmasq/dnsmasq.conf

cp -R /var/opt/syslinux/* /var/opt/instapxe/

# Start dnsmasq
dnsmasq --no-daemon --conf-file=/pxe/dnsmasq/dnsmasq.conf $_dnsmasq_flags
